### ISSUE TITLE
Remove over-emphasis on object-orientation

### ISSUE THREAD

**Issue by alexkalderimis** [exercism/xperl5#100]
Many of the exercises require an object to be created from a single value (often a number or string) only to call one method on it. This ends up feeling very Rubyish, which makes sense, but there is no need for objects in most of these cases, and a simple functional API would make the most sense.

**Comment by kytrinyx** [comment]
Agreed. In Ruby (and other languages) we've been tweaking a number of the exercises to not require object instantiation.
