### ISSUE TITLE
Consider re-ordering exercises in config.json

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xperl5#41]
Right now it looks like the exercises have been reordered to be alphabetical, which isn't necessarily the most useful progression.

I'd recommend trying to make a rough guess at which exercises are easier and move them towards the front of the list, and which ones are harder and move them to the end of the list.

**Comment by alexkalderimis** [comment]
As can be expected, a lot of the string manipulation ones are trivial in Perl - RNA transcription is a particular offender here (it is just `tr/CGTA/GCAU/`).

**Comment by kytrinyx** [comment]
Yeah, that's about what it is in ruby, as well. It might be worth sticking it on the "deprecated" list.
