### ISSUE TITLE
Recommend a linter for Perl?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xperl5#75]
This may or may not be appropriate in this language. See exercism/docs#54 for details.

**Comment by alexkalderimis** [comment]
[Perl-Critic](http://search.cpan.org/dist/Perl-Critic/bin/perlcritic) is fairly standard. But there are others.

**Comment by kytrinyx** [comment]
I think it's great to go with standards/common choices where possible.

**Comment by alexkalderimis** [comment]
One thing to be wary of is that automated linting tools are not always very popular in Perl (see the animated discussion on [this post](http://www.perlmonks.org/?node_id=989115)). The prevailing philosophy of TIMTOWTDI means it is very difficult to come up with a set of rules that pleases everyone (I have my own niggles about things in PBP to be honest). This is in marked contrast to the situation in other languages, such as Python where pep8 is the holy text.

**Comment by kytrinyx** [comment]
Yeah, in languages where there's no consensus, I think the most important thing would be to link to a linter as well one or more discussions about pros/cons so that people are aware of the role that a linter has in the community.

**Comment by yanick** [comment]
That documentation should go under `docs/TOOLS.md`, right?

**Comment by kotp** [comment]
Yes, I believe that is the place for it.

**Comment by yanick** [comment]
#134 was merged, so this can probably be closed.

**Comment by kotp** [comment]
Those were only mentions, not implementations.  But we can close until we are ready to place something here.  At the moment there is no CI (Travis) checks being done for letting us know, and that means that all lint/style type checks must/should be done by hand.

So should we close, or should we leave it open?  We can pin it, if it is something we think should be done, until someone can tackle it.

**Comment by kotp** [comment]
As per @yanick [comments](https://github.com/exercism/xperl5/issues/75#issuecomment-97834696) I think it is fair to close this as addressed.
